### ISSUE TITLE
Searching for italy changes the text to itsly

### ISSUE THREAD

**Issue by federicotorrielli** [lehinevych/MediaWikiAPI#39]
As the title says, invoking the command `mediawikiapi.page("Italy")` gives the following PageError:
`mediawikiapi.exceptions.PageError: Page id "itsly" does not match any pages. Try another id!`
But if we input the command `mediawikiapi.search("Italy")` it searches fine.

Python version tested: 3.8.0+ and 3.9.0 (same errors on both versions)

**Comment by lehinevych** [comment]
The issue is that suggestion feature returns misspelt word (should be `italy` instead of `itsly`). This is temporary issue on wiki side. In order to get the desire response you can simply disable autosuggestion.
```
page = mediawikiapi.page(title="Italy", auto_suggest=False)
```

In most cases autosuggestion help to find desire page but in this concrete example it's actually fails. I'm considering to disable this feature by default to avoid ambiguity in the future (it may provide you with different page than you searched)

**Comment by federicotorrielli** [comment]
Oh, understood. Thanks for the heads up!
